name: stepbystep
services:
    php:
        container_name: stepbystep.php
        hostname: stepbystep.php
        restart: unless-stopped
        image: sail:php82
        # build:
        #     context: .
        #     dockerfile: ./sail_client/php/Dockerfile
        # entrypoint: /bin/sh
        # stdin_open: true
        # tty: true
        # privileged: true
        volumes:
            - ./:/var/www
            - ./builders/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./builders/supervisor/php-fpm.ini:/etc/supervisor.d/php-fpm.ini
        networks:
            - app
            - proxy

    nginx:
        container_name: stepbystep.nginx
        hostname: stepbystep.back
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
             - "8080:80"
        volumes:
            - ./:/var/www
            # - ./builders/common/nginx.dev.conf/:/etc/nginx/conf.d/dev.conf
            - ./builders/common/nginx-http.conf:/etc/nginx/nginx.conf
            - ./builders/common/nginx-server.conf:/etc/nginx/http.d/default.conf
        networks:
            - app
            - proxy

    nodejs:
        container_name: stepbystep.nodejs
        hostname: stepbystep.front
        image: sail:node18
        tty: true
        restart: unless-stopped
        # ports:
        #     - "80:5173"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app
            - proxy
networks:
  app:
    name: stepbystep

  proxy:
    name: proxy
    external: true
